version: '1'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/BearBazaar?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: BearBazaar
        MYSQL_ROOT_PASSWORD: secret
        TZ: UTC
    ports:
      - "6000:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
