version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: twitch
      MYSQL_ROOT_PASSWORD: secret
      TZ: UTC
    volumes:
      - mysql-local:/var/lib/mysql
    ports:
      - 3306:3306

# permanent storage of data.
volumes:
  mysql-local: